#!/usr/bin/env bash
# Note: We DO NOT delete the files on destination on purpose, to give us
# a chance to get back files if we happen to have them wrongly deleted on local.
# This happened once, I don't want it to happen again

rsync \
      --chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r \
      --verbose \
      --archive \
      --update \
      --prune-empty-dirs \
      --copy-links \
      --compress \
      ./dist/ \
      pixelastic:/var/www/kirintor.pixelastic.com/
echo "Available on http://kirintor.pixelastic.com/"
